#
###################################
# Site wide configuration
####################################
#
title: Emilie
email: emiliempark@gmail.com
description: A simple and awesome blog theme powered by jekyll.
url: # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          Pacific/Auckland
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Emilie Park
  avatar: 
  job: "UX Engineer"
  bio: "Design UI/UX and front-end development, React JS and Native player"
  email: emiliempark@gmail.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: emiliempark
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: emiliempark
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
